# Generated by Django 3.2 on 2023-11-02 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='creat_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.level', verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='level',
            name='percent',
            field=models.IntegerField(help_text='（请输入0-100的整数表示百分比。例如：90表示90%）', verbose_name='折扣'),
        ),
    ]
