# Generated by Django 3.2 on 2023-11-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20231102_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='creat_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
    ]
